title = "Neurolina"
baseURL = "https://neurolina.github.io/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "There is only one thing that makes a dream impossible to achieve: the fear of failure. ― Paulo Coelho"
  facebook = ""
  twitter = ""
  instagram = "https://www.instagram.com/gandolinalee/"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/Dt_Reitpony_Gandalf70880.JPG"
  recent_posts_number = 2
